sudo: required
language: python
python:
  - "3.7"

cache:
  - pip

install:
  - pip install kin-sdk==2.2.3

before_script: 
  - cd scripts

script:
  - python -m pytest -v -rs -s -x --fulltrace --disable-warnings tests
